config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'homebis', to: 'pages#homebis', as: :homebis
  get 'hometris', to: 'pages#hometris', as: :hometris

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :mobile, :address, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :mobile, :address, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>mytemplate</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  <!--  <%= stylesheet_pack_tag 'application', media: 'all' %>  Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"></script>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <script>
      $(".num").counterUp();
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main-container">

  <div class="container-404">
    <h1 data-text="404">404</h1>
  </div>

  <div class="container-home text-center">
  </div>
</div>

app/views/pages/homebis.html.erb
<div class="main-container">

  <div class="layout layout-first">
    <div class="introduction text-center">
      <h1>INTRODUCTION</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita molestias voluptatum modi, saepe animi nam explicabo at inventore ipsa. Voluptas.</p>
    </div>
  </div>

  <div class="layout layout-second">
    <div class="primero">
      <%= image_tag ('chat-1.png') %>
    </div>
    <div class="segundo">
      <h2>CHAT ou CHAT</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, et earum, quaerat accusamus voluptatum excepturi optio tempore sequi veritatis praesentium doloremque consequatur quod, quisquam consequuntur ipsa id ducimus ullam ipsum. Dignissimos a, dolore harum.</p>
    </div>
  </div>

  <div class="layout layout-third">
    <div class="row">
      <div class="col-sm-6 d-flex flex-column align-items-center justify-content-center px-5">
        <h2>Looking for my way</h2>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis nihil libero iure, excepturi temporibus dignissimos officia quidem maxime magnam rerum hic nemo, aliquam numquam saepe earum inventore omnis eos. Provident.</p>
      </div>
      <div class="col-sm-6 picture">
        <%= image_tag ('picture-1.png') %>
      </div>
    </div>
  </div>

  <div class="layout layout-fourth">
  </div>

  <div class="layout layout-blog">
    <div class="blog-title text-center">
      <h1>My Blog</h1>
    </div>
    <div class="blog-wrapper">
      <div class="blog">
        <%= image_tag ('coffee-1.jpg') %>
        <div class="blog-content p-3">
          <h4>Title three</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut illo rem doloribus debitis consectetur totam ipsam, repellat, consequuntur quam unde ullam provident rerum, quam unde ullam provident rerum.
          </p>
        </div>
      </div>
      <div class="blog">
        <%= image_tag ('coffee-2.jpg') %>
        <div class="blog-content p-3">
          <h3>Title two</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut illo rem doloribus debitis consectetur totam ipsam, repellat, consequuntur.
          </p>
        </div>
      </div>
      <div class="blog">
        <%= image_tag ('coffee-3.jpg') %>
        <div class="blog-content p-3">
          <h4>Title three</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut illo rem doloribus debitis consectetur totam ipsam, repellat, consequuntur quam unde ullam provident rerum, quam unde ullam provident rerum, inventore officiis inventore officiis.
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/hometris.html.erb
<div class="section section-one">
  <div class="site-title text-center" data-aos="fade-right">
    <h1>Léo Balzac</h1>
    <p>Stratégie & Communication Digitales</p>
  </div>
</div>

<div class="section section-two">
  <div class="text">
    <p>L’Agence Léo Balzac contribue à accroître la notoriété des acteurs de la sphère artistique et culturelle.</p>
    <p>En établissant une stratégie de communication claire et pragmatique, elle développe leur visibilité et renforce les liens avec leurs clients et visiteurs.</p>
    <p>Ses actions permettent de constituer des communautés de soutien notamment via des projets de financement participatif.</p>
  </div>
</div>

<div class="section section-three" >
  <div class="title">
    <h1>NOS SERVICES</h1>
  </div>
  <div class="wrap-cards">
    <div class="card">
      <i class="fas fa-lightbulb fa-3x"></i>
      <h3>Stratégie Digitale</h3>
    </div>
    <div class="card">
      <i class="fas fa-desktop fa-3x"></i>
      <h3>Site Internet Vitrine</h3>
    </div>
    <div class="card">
      <i class="fas fa-dollar-sign fa-3x"></i>
      <h3>Financement Participatif</h3>
    </div>
    <div class="card">
      <i class="fab fa-facebook-square fa-3x"></i>
      <h3>Animation Facebook</h3>
    </div>
    <div class="card">
      <i class="fab fa-instagram fa-3x"></i>
      <h3>Animation Instagram</h3>
    </div>
    <div class="card">
      <i class="fab fa-pinterest-square fa-3x"></i>
      <h3>Animation Pinterest</h3>
    </div>
  </div>
</div>

<div class="section section-four">
  <div class="title-w">
    <h1>POUR LE COMPTE DE NOS CLIENTS NOUS GERONS AUJOURD'HUI</h1>
  </div>
  <div class="wrap-counters">
    <div class="counter">
      <div class="num">17</div>
      <br>
      communautés
    </div>

    <div class="counter">
      <div class="num">356</div>
      <br>
      publications
    </div>

    <div class="counter">
      <div class="num">803</div>
      <br>
      membres
    </div>
  </div>
</div>

<div class="section section-five">
  <div class="title">
    <h1>QUELQUES CLIENTS</h1>
  </div>
  <div class="wrap-client-cards">
    <div class="client-card">
      <div class="client-card-image">
        <%= image_tag('logo-estrine.jpg') %>
      </div>
      <div class="client-card-links">
        <ul class="list-links">
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-meetup"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-instagram"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-slack"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="client-card-title text-center">
        <h5>Musée Estrine - St Rémy de Provence</h5>
      </div>
    </div>
    <div class="client-card">
      <div class="client-card-image">
        <%= image_tag('camando.jpg') %>
      </div>
      <div class="client-card-links">
        <ul class="list-links">
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-facebook-f"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-wordpress"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-twitter"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="client-card-title text-center">
        <h5>Fan Page Musée Nissim de Camondo - Paris</h5>
      </div>
    </div>


    <div class="client-card">
      <div class="client-card-image">
        <%= image_tag('logo-canu.jpg') %>
      </div>
      <div class="client-card-links">
        <ul class="list-links">
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-snapchat"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-linkedin"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fas fa-globe"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="client-card-title text-center">
        <h5>Artiste peintre - St Rémy de Provence</h5>
      </div>
    </div>


    <div class="client-card">
      <div class="client-card-image">
        <%= image_tag('logo-sha.jpg') %>
      </div>
      <div class="client-card-links">
        <ul class="list-links">
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-twitter"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-instagram"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="client-card-title text-center">
        <h5>Association SHA - St Rémy de Provence</h5>
      </div>
    </div>

    <div class="client-card">
      <div class="client-card-image">
        <%= image_tag('logo-caron.jpg') %>
      </div>
      <div class="client-card-links">
        <ul class="list-links">
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-pinterest-p"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fab fa-instagram"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fas fa-globe"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="client-card-title text-center">
        <h5>Caron & Associés - Architecte d'Intérieur</h5>
      </div>
    </div>

  </div>
</div>

<div class="section-six" id="contact-form">
  <div class="wrap-form">
    <div class="title">
      <h1>CONTACTEZ NOUS</h1>
    </div>
    <form id="fs-frm" name="simple-contact-form" accept-charset="utf-8" action="https://formspree.io/benoit.bessiere@me.com" method="post">
      <fieldset id="fs-frm-inputs">
        <input type="text" name="name" id="name" placeholder="Nom" required="">
        <input type="text" name="name" id="phone" placeholder="Téléphone" required="">
        <input type="email" name="_replyto" id="email" placeholder="Email" required="">
        <textarea rows="3" name="message" id="msg" placeholder="Message" required=""></textarea>
        <input type="hidden" name="_subject" id="email-subject" value="Formulaire balzac.com">
      </fieldset>
      <input id="button" type="submit" value="Envoyer">
    </form>
  </div>
</div>

<footer>
  <div class="text-center">
    <p>©LéoBalzac 2019</p>
  </div>
</footer>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-classic">
  <div class="footer-classic-header">
    <h5>Follow us :</h5>
  </div>
  <div class="footer-classic-links">
    <ul>
      <li><a href="#"><i class="fab fa-github" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-google-plus-g" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-linkedin-in" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-medium-m" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-meetup" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-slack" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-snapchat" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-skype" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-vimeo" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fab fa-youtube-square" aria-hidden="true"></i></a></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-classic">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-classic-brand" do %>
    <%= image_tag("logo.png") %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-classic-right">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "homebis", homebis_path, class: "navbar-classic-item navbar-classic-link" %>
      <%= link_to "hometris", hometris_path, class: "navbar-classic-item navbar-classic-link" %>
      <%= link_to "Menu", "#", class: "navbar-classic-item navbar-classic-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-classic-item">
        <div class="dropdown">
          <%= image_tag ("droopy.png"), class: "avatar dropdown-toggle", id: "navbar-classic-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-classic-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fas fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fas fa-cog"></i> <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to new_user_session_path do %>
        <i class="fas fa-sign-in-alt fa-2x"></i> <%= t('.sign_in', default: "") %>
      <% end %>
    <% end %>
  </div>
</div>